apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    log-type: fluent-bit
    logging-disabled: "false"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        log-type: fluent-bit
        logging-disabled: "false"
    spec:
      containers:
      - name: fluent-bit
        image: benjvi/fluent-bit-humio-kubernetes-daemonset:0.11
        env:
          - name: FLUENT_HUMIO_HOST
            value: "go.humio.com"
          - name: FLUENT_HUMIO_DATA_SPACE
            value: "KubeIntegration"
          - name: FLUENT_HUMIO_INGEST_TOKEN
            valueFrom:
              secretKeyRef:
                name: fluent-bit-humio-ingest-token
                key: token
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
